---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/s0undt3ch/python-tools-scripts
    rev: "0.18.6"
    hooks:
      - id: tools
        alias: cleanup-duplicates
        name: Fix duplicate entries and sort files
        pass_filenames: false
        files: ^.*\.txt
        args:
          - pre-commit
          - cleanup-duplicates

  # ----- Formatting ------------------------------------------------------------------------------------------------>
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.280"
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: (.pre-commit-hooks/.*|docs/.*)\.py
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.9+
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [-l 100]
  # <---- Formatting -------------------------------------------------------------------------------------------------
